[package]
name = "contacts"
version = "0.1.0"
authors = ["zach tuttle <tuttle_zach@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "*"
serde   = "*"
serde_derive = "*"
app_dirs = "^1.2.1"